from alttester.commands.ObjectCommands.call_method import *
from alttester.commands.ObjectCommands.get_all_components import *
from alttester.commands.ObjectCommands.get_component_property import *
from alttester.commands.ObjectCommands.get_text import *
from alttester.commands.ObjectCommands.set_text import *
from alttester.commands.ObjectCommands.pointer_down import *
from alttester.commands.ObjectCommands.pointer_enter import *
from alttester.commands.ObjectCommands.pointer_exit import *
from alttester.commands.ObjectCommands.pointer_up import *
from alttester.commands.ObjectCommands.set_component_property import *
from alttester.commands.ObjectCommands.tap_element import *
from alttester.commands.ObjectCommands.click_element import *
