from alttester.commands.InputActions.begin_touch import *
from alttester.commands.InputActions.click_coordinates import *
from alttester.commands.InputActions.end_touch import *
from alttester.commands.InputActions.keys_down import *
from alttester.commands.InputActions.keys_up import *
from alttester.commands.InputActions.move_mouse import *
from alttester.commands.InputActions.move_touch import *
from alttester.commands.InputActions.multi_point_swipe import *
from alttester.commands.InputActions.press_keys import *
from alttester.commands.InputActions.scroll_mouse import *
from alttester.commands.InputActions.swipe import *
from alttester.commands.InputActions.tap_coordinates import *
from alttester.commands.InputActions.tilt import *
