name: release build

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]"

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet build --configuration Release /p:Version=${VERSION} --output .
      working-directory: src
#    - name: Push
#      run: dotnet nuget push NUnit.Allure.${VERSION}.nupkg -s https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
#      working-directory: src
#      env:
#        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}