name: Actions for issues just created
on:
  issues:
    types: [opened]
jobs:
  add-to-project:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project-url: https://github.com/orgs/alttester/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
          