name: Push
on:
  push:
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: [self-hosted, macOS]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cached: 'pip'
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: pip install -r Docs/requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - run: pwd
      - uses: rickstaa/sphinx-action@master
        with:
          docs-folder: Docs
          build-command: make html

      - uses: actions/upload-artifact@v3.1.0
        if: always() # run this step even if one of the previous step failed
        with:
          name: DocumentationHTML
          path: Docs/build/html/

  dev-docs:
    runs-on: [self-hosted, macOS]
    needs: build-docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3.0.0
        with:
          name: DocumentationHTML
          path: DocumentationHTML/
      - name: Upload dev documentation
        env:
          HOST_IP_ALTOM: ${{ secrets.HOST_IP_ALTOM }}
          DOCUMENTATION_PATH: ${{ secrets.DOCUMENTATION_PATH }}
        run: |
          ssh -o 'StrictHostKeyChecking no' altomdotcom@35.204.11.13 -p 34168  "rm -rf /www/altomdotcom_241/public/current/web/alttester/docs/sdks/*"
          scp -r -P 34168 -o 'StrictHostKeyChecking no' DocumentationHTML/* altomdotcom@35.204.11.13:/www/altomdotcom_241/public/current/web/alttester/docs/sdks
