name: Pipeline for WebGL

on: 
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0' # run on every Sunday

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  build-WebGL-Unity2021:
      runs-on: [self-hosted, macOS]
      steps:
        - uses: actions/checkout@v3

        - run: |
            export PROXY_PORT=13010
            export PROXY_HOST="127.0.0.1"
            $UNITY_2021_3_HOME -batchmode -stackTraceLogType None -projectPath $CI_PROJECT_DIR -executeMethod AltTesterTools.BuildAltTester.WebGLBuildFromCommandLine -logFile buildWebGL.log -quit

        - uses: actions/upload-artifact@v3.1.0
          if: always() # run this step even if one of the previous step failed
          with:
            name: BuildWebGLArtifact
            path: |
              build
              buildWebGL.log

  test-DotNet:
      runs-on: [self-hosted, macOS]
      needs: build-WebGL-Unity2021
      steps:
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3.0.0
          with:
            name:
              BuildWebGLArtifact
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v2.1.1
        - run: |
            export PROXY_PORT=13010
            echo $PROXY_PORT
            export PROXY_HOST="127.0.0.1"
            cd build/webgl
            python3 -m http.server --cgi 8360 &
            osascript -e 'quit app "Chrome"'
            open http://localhost:8360/index.html
            cd ../..
            dotnet test Bindings~/dotnet/AltDriver.Tests/AltDriver.Tests.csproj --logger:"console;verbosity=detailed" --filter TestCategory!=WebGLUnsupported

        - name: Close Chrome
          if: always() 
          run: osascript -e 'quit app "Chrome"'

        - uses: actions/upload-artifact@v3.1.0
          if: always() # run this step even if one of the previous step failed
          with:
            name: TestCSharpArtifact
            path: |
              *.log

  test-Python:
      runs-on: [self-hosted, macOS]
      needs: build-WebGL-Unity2021
      steps:
        - uses: actions/checkout@v3

        - uses: actions/download-artifact@v3.0.0
          with:
            name:
              BuildWebGLArtifact

        - name: Open application
          run: |
            export PROXY_PORT=13010
            export PROXY_HOST="127.0.0.1"
            cd build/webgl
            python3 -m http.server --cgi 8360 &
            osascript -e 'quit app "Chrome"'
            open http://localhost:8360/index.html
            cd ../..

        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            pip install --upgrade pip setuptools wheel
            pip uninstall AltTester-Driver
            pip install -r "Bindings~/python/requirements.txt"
            pip install -r "Bindings~/python/requirements-dev.txt"
            pip install -e "Bindings~/python" --root "Bindings~/python"

        - name: Lint with flake8
          run: |
            flake8 Bindings~/python/ --config Bindings~/python/.flake8

        - name: Run unit tests
          run: |
            pytest Bindings~/python/tests/unit -m "not WebGLUnsupported"

        - name: Run integration tests
          run: |
            export PROXY_PORT=13010
            export PROXY_HOST="127.0.0.1"
            pytest Bindings~/python/tests/integration -m "not WebGLUnsupported"

        - name: Close Chrome
          if: always() 
          run: osascript -e 'quit app "Chrome"'

        - uses: actions/upload-artifact@v3.1.0
          if: always() # run this step even if one of the previous step failed
          with:
            name: TestPythonArtifact
            path: "**/*.log"

  test-Java:
      runs-on: [self-hosted, macOS]
      needs: build-WebGL-Unity2021
      steps:
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3.0.0
          with:
            name:
              BuildWebGLArtifact

        - name: Setup Java JDK
          uses: actions/setup-java@v3.5.1
          with:
              distribution: temurin
              java-version: 11
        - uses: stCarolas/setup-maven@v4.4
        - run: |
            export PROXY_PORT=13010
            echo $PROXY_PORT
            export PROXY_HOST="127.0.0.1"
            cd build/webgl
            python3 -m http.server --cgi 8360 &
            osascript -e 'quit app "Chrome"'
            open http://localhost:8360/index.html
            cd ../../Bindings~/java
            mvn clean  -Dtest=com.alttester.Tests* test -Dgroups=\!WebGLUnsupported

        - name: Close Chrome
          if: always() 
          run: osascript -e 'quit app "Chrome"'

        - uses: actions/upload-artifact@v3.1.0
          if: always() # run this step even if one of the previous step failed
          with:
            name: TestJavaArtifact
            path: |
              *.log